version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
skip_tags: true
clone_depth: 1
install:
- set BUILD_DIR=%CD%
- set BOOST_ROOT=c:\Libraries\boost_1_67_0
- set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
- echo %BOOST_ROOT%
- echo %BOOST_BUILD_PATH%
- set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
- set PATH=c:\msys64\mingw32\bin;%PATH%
- g++ --version
- copy user-config.jam %HOMEDRIVE%%HOMEPATH%\user-config.jam
- cd %BOOST_BUILD_PATH%\src\engine
- build.bat >nul
- cd %BUILD_DIR%
environment:
  matrix:
  - compiler: msvc-14.1
  - compiler: gcc
build_script:
- b2.exe --hash warnings-as-errors=on -j2 address-model=32 %compiler%

